import React, { Fragment } from 'react'
import Link from 'next/link';
import Head from 'next/head';

function Layout({ children, title }) {
  return (
    <Fragment>
        <Head>
            <title>{ title ? title + ' - Amazon' : 'Amazon'}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* OVERALL LAYOUT FOR ALL PAGES */}
        <div className="flex min-h-screen flex-col justify-between">
            {/* NavBar */}
            <header>
                <nav className="flex h-12 justify-between items-center shadow-md px-4">
                    <Link href="/">
                        <a className="text-lg font-bold">amazon</a>
                    </Link>
                    <div>
                        <Link href="/cart"><a className="p-2">Cart</a></Link>
                        <Link href="/cart"><a className="p-2">Login</a></Link>
                    </div>
                </nav>
            </header>
            {/* Main section */}
            <main className="container m-auto mt-4 px-4">{ children }</main>
            {/* Footer */}
            <footer className="flex justify-center items-center h-10 shadow-inner">
                <p>Copyright &copy; 2022 Amazon</p>
            </footer>
        </div>
    </Fragment>
  
  )
}

export default Layout
